trigger:
- main
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
   dispalyName:'dotnet build $(buildConfiguration)'
   